### ISSUE TITLE
経理アシスタント（パートタイム）のポジションをコーポレイトの下に追加してほしい

### ISSUE THREAD

**Issue by sayakatakayama** [DenkiYagi/EmployeeHandbook#18]
下記のポジションを追加してください。

------------------------------------------------------------------------------
Job Title：
経理アシスタント(パートタイム)

業務内容：
日々の入出金および請求書の会計計上
日々の顧客分別金信託所要額のモニタリング
日々及び月次支払のウェブバンキング申請
月次会計計上処理
※週2日それぞれ6時間が目安（勤務日、時間帯応相談）

求める人物像・スキル：
【必要なスキルや経験】
簿記3級程度の経理知識
事務処理・ファイリングなどの実務経験
証憑にもとづいた記帳など正確な処理のできる方

【歓迎するスキルや経験】
簿記２級程度の経理知識
経理・税務関連業務の経験
規則・法令等を読むことに抵抗のない方

**Comment by terurou** [comment]
経理アシスタントは担当役員および一部外注で概ね不自由が発生していないため、募集予定がありません。
パートタイムの総務であれば、検討の余地はあります。

**Comment by sayakatakayama** [comment]
大変失礼しました。投稿先を間違えてIssueを立ててしまいました。こちら後ほど削除いたします。申し訳ございませんでした。
