### ISSUE TITLE
安全衛生関連の記述量が足りない

### ISSUE THREAD

**Issue by terurou** [DenkiYagi/EmployeeHandbook#22]
インフルエンザ等の対応など、もっとわかりやすくすべき
http://zaimupartners.biz/roumunoonayamihakenhukumu/infulenza/

**Comment by Takashi-U** [comment]
https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/roudoukijun/zigyonushi/model/index.html

モデル就業規則の第9章が安全衛生関連の条項になります。
例えばですが、先ずは

* モデル就業規則の第9章（の一部）を基にする。
* 遵守事項に御社の希望する記述を追記する。
* 今後の加筆修正を鑑みて別規程にする。

という対応をしてみてはいかがでしょうか。

記述量が足りない部分については、遵守事項のに項をつけたり号を加えたり、場合によっては条をつけても良いと思います。
要は、安全衛生関係で義務づけられている事柄を守って頂くという事と、事業主の義務として職場の環境を守るという事を実現するわけですから、基本的には禁止事項や制限事項を加えていく事が多いと思います。
インフルエンザが例に出ておりますが、インフルエンザの場合は罹患している事の報告を義務づけたり、出勤停止にしたりという事を追記していくところでしょう。

何れにしても、タスクの粒度的に先程列挙した変更をご検討いただき、個別の条項（例えばインフルエンザの条項追加など）についてissueを立てる形にして、このissueをcloseさせるのは一つのアイデアかと思っております。

**Comment by terurou** [comment]
issueを分割しました
